export const SET_CUSTOMER_AUTH = 'SET_CUSTOMER_AUTH';
export const SET_BUSINESS_AUTH = 'SET_BUSINESS_AUTH';
export const REMOVE_AUTH = 'REMOVE_AUTH';

export const CREATE_CUSTOMER_USER = 'CREATE_CUSTOMER_USER';
export const CREATE_BUSINESS_USER = 'CREATE_BUSINESS_USER';

export const UPDATE_ORDER = 'UPDATE_ORDER';
